# Generated by Django 5.1.9 on 2025-05-15 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('category', models.CharField(blank=True, choices=[('Проблемы с интернетом', 'Проблемы с интернетом'), ('Проблемы с периферийным оборудованием', 'Проблемы с периферийным оборудованием'), ('Проблемы с электронной почтой', 'Проблемы с электронной почтой'), ('Другие проблемы', 'Другие проблемы')], max_length=64, null=True)),
                ('comment', models.CharField(max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('обрабатывается', 'обрабатывается'), ('не назначен', 'не назначен'), ('завершен', 'завершен')], default='не назначен', max_length=20)),
            ],
            options={
                'db_table': 'form',
                'permissions': [('can_assign_form', 'Can assign forms to employees')],
            },
        ),
        migrations.CreateModel(
            name='FormAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('не назначен', 'не назначен'), ('обрабатывается', 'обрабатывается'), ('завершен', 'завершен')], default='не назначен', max_length=20)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.form')),
            ],
            options={
                'db_table': 'form_assignment',
            },
        ),
    ]
