# Generated by Django 5.1.9 on 2025-05-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_assign_form', 'Can assign forms to employees')]},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={},
        ),
    ]
